### ISSUE TITLE
it returl error like  "psql: FATAL:  Peer authentication failed for user "postgres""

### ISSUE THREAD

**Issue by kartikdanidhariya** [divio/django-cms-demo#67]
hi,
 i want to create django-cms-demo installation in my system 
whem i give command like 
make install 
so it return error 

make[1]: Leaving directory `/home/keyur/django_cms_3.2/django-cms-demo-master'
make database
make[1]: Entering directory `/home/keyur/django_cms_3.2/django-cms-demo-master'
psql -U postgres -c 'DROP DATABASE djangocms_demo_local;'
psql: FATAL:  Peer authentication failed for user "postgres"
make[1]: [database] Error 2 (ignored)
psql -U postgres -c 'CREATE DATABASE djangocms_demo_local;'
psql: FATAL:  Peer authentication failed for user "postgres"
make[1]: *** [database] Error 2
make[1]: Leaving directory `/home/keyur/django_cms_3.2/django-cms-demo-master'
make: *** [install] Error 2

after i try to create db manually in my local system but still it return error
pls help how can i solve this error

**Comment by FinalAngel** [comment]
Hello @kartikdanidhariya the demo project runs currently on the unreleased 3.2.1 branch for testing. Your mentioned problem has been fixed on Friday, so doing another `make install` after pulling should do it.

If you wanna go save just change the following line: https://github.com/divio/django-cms-demo/blob/master/requirements.txt#L7

to

https://github.com/divio/django-cms/archive/master.zip

**Comment by kartikdanidhariya** [comment]
hi,
Thanks for reply, download latest zip from your repo and after when i give make install command so it return same error 
so how can i solve

**Comment by FinalAngel** [comment]
@kartikdanidhariya what postgres user do you have? The install script assumes you have the default "postgres" user enabled:

https://github.com/divio/django-cms-demo/blob/master/Makefile#L8

You can override using ``make install DBUSER=myCustomUser``
