### ISSUE TITLE
Initial Database Data

### ISSUE THREAD

**Issue by Nekmo** [divio/django-cms-demo#83]
Hello, I'm going to do a presentation of Django CMS in an event, and would need an offline version of the Demo (https://control.aldryn.com/demo/get-new/). Although here is the source code, the data in the database is not found here.

I would need a dump of the database to be able to create a project in local, just like it is in the online demo.

Thank you very much.

**Comment by FinalAngel** [comment]
Hello @Nekmo you can easily get the exact demo by creating a project on Divio Cloud using the "Explorer Theme" and then set it up locally using "divio project setup {name}". That way it runs locally & offline.

The source code here is not the one used on the Divio Cloud demo. This is a testing project and has no real data.

**Comment by Nekmo** [comment]
Thanks!
